apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-secret
type: Opaque
stringData:
  DatabaseConnection__Password: "__DB_MASTER_PASSWORD__"
  Jwt__Key: "xmvsLe9QxIR3BWAWJW4wL+5ZfZrYaohxUaRYSkxteiAn5qEAKDd3xCMn1Bk46ndy6sl4gkVXXvEP/1JowbBp/g=="
  ApiCredentials__ClientSecret: "admin"
  Webhook__HmacSecret: "63f4945d921d599f27ae4fdf5bada3f1"
  NEW_RELIC_LICENSE_KEY: "__NEW_RELIC_LICENSE_KEY__"