apiVersion: v1
kind: Service
metadata:
  name: ordemservico-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ordemservico-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30083
